#!/usr/bin/expect -f

set timeout 20
set host "72.61.229.171"
set user "root"
set password ")vbofQi/lHXSMqF?Nk8E"

spawn ssh -o StrictHostKeyChecking=no $user@$host "echo 'SSH Connection Successful'"

expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    "SSH Connection Successful" {
        exit 0
    }
    timeout {
        puts "Connection timed out"
        exit 1
    }
    eof {
        puts "Connection failed"
        exit 1
    }
}
