#!/usr/bin/expect -f
set timeout 600
set host "72.61.229.171"
set user "root"
set password ")vbofQi/lHXSMqF?Nk8E"

spawn ssh -o StrictHostKeyChecking=no $user@$host "cd /var/www/qr.akmal.in && pm2 delete qr-frontend || true && rm -rf .next && NEXT_PUBLIC_BASE_URL=https://qr.akmal.in npm run build && pm2 start npm --name 'qr-frontend' -- start -- -p 3002 && pm2 save"

expect {
    "password:" {
        send "$password\r"
    }
}
expect eof
